### PR TITLE
Fixed docker daemon detection on opensuse

### PR DESCRIPTION
**Pull request by niriak**
Fixed process detection of docker daemon running on openSUSE (tested on 13.2).

Example docker daemon process on opensuse:
/usr/bin/docker -d -H fd://

### CODE REVIEW

**Comment by zedtux** [comment]
Thank you @niriak for this. Unfortunatelly it's breaking the daemon detection on Debian.

**Comment by niriak** [comment]
> Thank you @niriak for this. Unfortunatelly it's breaking the daemon
> detection on Debian.

Sorry for this, I was hoping using a regular expression with debian's "daemon" 
and opensuse's "-d" option would do the trick. Do you have an idea why it's 
not working anymore on debian?

I've tried both options on both dockerized OSs on my opensuse 13.2 server:

Default opensuse setup ("-d")

	docker run -it --pid=host debian ps ax | grep -e "docker \(-d\|daemon\)" | grep -v grep                                                                                                       
	 1707 ?        Rsl    0:08 /usr/bin/docker -d -H fd://

	docker run -it --pid=host opensuse ps ax | grep -e "docker \(-d\|daemon\)" | grep -v grep      
	 1707 ?        Ssl    0:08 /usr/bin/docker -d -H fd://

Customized opensuse setup ("daemon")

	docker run -it --pid=host opensuse ps ax | grep -e "docker \(-d\|daemon\)" | grep -v grep
	16320 ?        Ssl    0:00 /usr/bin/docker daemon -H fd://

	docker run -it --pid=host debian ps ax | grep -e "docker \(-d\|daemon\)" | grep -v grep
	16320 ?        Ssl    0:00 /usr/bin/docker daemon -H fd://

**Comment by jawz101** [comment]
Seems like it'd fix Arch Linux 64 bit as well.  I tried running the previous ps grep from terminal and the revised one and the change in this commit actually returned the docker process running.

**Comment by zedtux** [comment]
Thank you @jawz101 for your feedback. Anyway now all the Linux support is merged in kitematic so this PR will never been merge here.

In case something needs to be changed, please open a PR on the kitematic repo.

**Pull request closed without merging**
